// <auto-generated />
using System;
using Ferrero.GestorDeProjetos.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ferrero.GestorDeProjetos.Web.Migrations
{
    [DbContext(typeof(ProjetosDBContext))]
    [Migration("20190520145258_InitialSchemaCreation")]
    partial class InitialSchemaCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ferrero.GestorDeProjetos.Web.Models.Ativo", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int?>("CentroDeCustoId");

                    b.Property<string>("Descricao");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("OrdemDeInvestimentoId");

                    b.Property<int>("Situacao");

                    b.HasKey("Id");

                    b.HasIndex("CentroDeCustoId");

                    b.HasIndex("OrdemDeInvestimentoId");

                    b.ToTable("Ativos");
                });

            modelBuilder.Entity("Ferrero.GestorDeProjetos.Web.Models.CentroDeCusto", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("CentrosDeCusto");
                });

            modelBuilder.Entity("Ferrero.GestorDeProjetos.Web.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("Ferrero.GestorDeProjetos.Web.Models.OrdemDeInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Numero");

                    b.Property<int?>("ProjetoId");

                    b.Property<decimal>("Valor")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnType("DECIMAL");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("OrdensDeInvestimento");
                });

            modelBuilder.Entity("Ferrero.GestorDeProjetos.Web.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Concluido");

                    b.Property<DateTime>("DataDeInicio")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("DataDeTermino")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("Ferrero.GestorDeProjetos.Web.Models.Ativo", b =>
                {
                    b.HasOne("Ferrero.GestorDeProjetos.Web.Models.CentroDeCusto", "CentroDeCusto")
                        .WithMany()
                        .HasForeignKey("CentroDeCustoId");

                    b.HasOne("Ferrero.GestorDeProjetos.Web.Models.OrdemDeInvestimento", "OrdemDeInvestimento")
                        .WithMany()
                        .HasForeignKey("OrdemDeInvestimentoId");
                });

            modelBuilder.Entity("Ferrero.GestorDeProjetos.Web.Models.OrdemDeInvestimento", b =>
                {
                    b.HasOne("Ferrero.GestorDeProjetos.Web.Models.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId");
                });
#pragma warning restore 612, 618
        }
    }
}
